import '../styles/globals.css';

import { userDummy, userReducerContext } from '../reducers/contextAPI';

import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useReducer } from 'react';
import userContext from '../constants/UserContext';
import wrapper from '../store/configureStore';

/*
  Redux와 ContextAPI 비교하기
*/
const MyApp = ({ Component }: AppProps) => {
  //Context API 사용하기
  const [user, dispatchUser] = useReducer(userReducerContext, userDummy);
  const providerValue: any = { user, dispatchUser };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <userContext.Provider value={providerValue}>
        <Component />
      </userContext.Provider>
    </>
  );
};

//Redux 사용하기
export default wrapper.withRedux(MyApp);
